# Add application configuration variables here, as shown below.

POSTGRES_HOST: localhost
POSTGRES_PASSWORD:
REDIS_HOST: localhost
ELASTICSEARCH_HOST: localhost

SECRET_KEY_BASE: 83daf5e7b80d990f037407bab78dff9904aaf3c195a50f84fa8695a22287e707dfbd9524b403b1dcf116ae1d8c06844c3d7ed942564e5b46be6ae3ead93a9d30
STRIPE_API_KEY:
STRIPE_PUBLISHABLE_KEY:
STRIPE_CURRENCY: 'eur'

INVOICE_PREFIX: FAB@CIC invoice
FABLAB_WITHOUT_PLANS: 'false'

DEFAULT_MAIL_FROM: Fab@CIC <noreply@fab-manager.com>

# For prod & staging env only
DEFAULT_HOST: fab-manager.com
DEFAULT_PROTOCOL: https
DELIVERY_METHOD: smtp
SMTP_ADDRESS:
SMTP_PORT: 587
SMTP_USER_NAME:
SMTP_PASSWORD:
GA_ID: ''
##

DISQUS_SHORTNAME:

TWITTER_NAME: '-'
TWITTER_CONSUMER_KEY: ''
TWITTER_CONSUMER_SECRET: ''
TWITTER_ACCESS_TOKEN: ''
TWITTER_ACCESS_TOKEN_SECRET: ''

RAILS_LOCALE: 'en'
MOMENT_LOCALE: 'en'
SUMMERNOTE_LOCALE: 'en-US'
ANGULAR_LOCALE: 'en-en'
MESSAGEFORMAT_LOCALE: 'en'
FULLCALENDAR_LOCALE: 'en'

ELASTICSEARCH_LANGUAGE_ANALYZER: 'english'

TIME_ZONE: 'UTC'
WEEK_STARTING_DAY: 'monday'
D3_DATE_FORMAT: '%d/%m/%y'
UIB_DATE_FORMAT: 'MM/dd/yyyy'

OPENLAB_APP_SECRET:
OPENLAB_APP_ID:
OPENLAB_BASE_URI: 'https://openprojects.fab-manager.com'
